name: hello-world
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy google
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: run ls
        run: ls -la

  test:
    runs-on: ubuntu-latest  
    name: teste deploy
    needs: deploy
    steps:
      - name: run whoami
        run: whoami

      - name: run pwd
        run: pwd
        
  test-env:
    runs-on: ubuntu-latest  
    name: teste env
    needs: deploy
    env: 
      ADDCONNECTION: ${{ secrets.ADDCONNECTION }}
    steps:
      - name: run echo
        run: echo $ADDCONNECTION

      - name: run pwd
        run: pwd

  test-env-development:
    runs-on: ubuntu-latest  
    name: teste env Development
    needs: deploy
    environment: Development
    env:
      MYSQL_PORT: ${{ secrets.ENV_MYSQL_PORT }}
    steps:
      - name: run whoami
        run: whoami

      - name: run pwd
        run: pwd        

  workflow-dispatch:
    runs-on: ubuntu-latest  
    name: teste workflows
    needs: test-env
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: rodrigomjr
          repo: workflow-dispatch
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: hello-world.yaml
#          client_payload: '{}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
    