name: hello-world
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy google
    steps:
      - name: my-step
        run: echo "Hello World!"

      - name: run ls
        run: ls -la

  test:
    runs-on: ubuntu-latest  
    name: teste deploy
    needs: deploy
    steps:
      - name: run whoami
        run: whoami

      - name: run pwd
        run: pwd
        
  test-env:
    runs-on: ubuntu-latest  
    name: teste env
    needs: deploy
    env: 
      ADDCONNECTION: mysql-test
    steps:
      - name: run echo
        run: echo $ADDCONNECTION

      - name: run pwd
        run: pwd
    